### ISSUE TITLE
Absurd results when using multiple cores

### ISSUE THREAD

**Issue by student982** [MultiBUGS/MultiBUGS#10]
Hi,
The model in question is a very simple beta regression with fixed effects.
When using 1 core, the results obtained are coherent and in line with what i expect.
I do 10000 iterations, and I observe convergence after ~1000 iterations with 2 chains. data is 10000 lines.
The problem appears when I do the exact same operation using 2 or 4 cores. The programm update correctly up to 10000 and is way faster than when using 1 core, but when i go to check the posteriors, I obtain completely different and absurd results, with variances of 30 on all my parameters.

To Resume, it's obvious there is something wrong with calculations when using multiple cores, but i have no idea what. Feel free to ask for details.

Any help appreciated, Thanks

**Comment by rjbgoudie** [comment]
Thanks for the report.

Are you able to provide code (model file, data, inits) that produces the problem? Ideally, a minimal, simple example. This will make it easier to debug your problem.

**Comment by student982** [comment]
Thanks for your quick response.
Here are the model specification and initials values for both chains (first file) and data for 100 (out of 10000) observations (second file).
[ModelTest100.txt](https://github.com/MultiBUGS/MultiBUGS/files/1970814/ModelTest100.txt)
[DataTest100.txt](https://github.com/MultiBUGS/MultiBUGS/files/1970817/DataTest100.txt)

**Comment by rjbgoudie** [comment]
Closing, fixed by 7dee319ab3677c54ce4b92a1176c0520a86ba578. Thanks again @student982 for nice and simple example of the bug :)

The problem was in GraphBeta. MultiBUGS was not externalizing / internalizing the field called normalize. This field asks the beta density to calculate normalizing constants and is needed when the beta is used as a likelihood as in this model.

Results now match up to MC error between OpenBUGS and MultiBUGS.

MultiBUGS (2 chains, 4 cores, 10000 burnin, 50000 post burn):
		mean	median	sd	MC_error	val2.5pc	val97.5pc	start	sample	ESS
	b0	0.6824	0.6831	0.1659	0.002433	0.3596	1.01	10001	100000	4648
	b1	-0.1971	-0.1954	0.1067	8.251E-4	-0.4099	0.00761	10001	100000	16725
	b2	-0.044	-0.04424	0.03268	4.768E-4	-0.1078	0.02051	10001	100000	4699
	b3	0.1236	0.1209	0.2358	0.002199	-0.3344	0.5949	10001	100000	11493
	b4	-0.3708	-0.3724	0.2815	0.002352	-0.9246	0.1917	10001	100000	14321
	phi	4.202	4.176	0.5423	0.00216	3.22	5.333	10001	100000	63018

OpenBUGS (2 chains, 10000 burnin, 50000 post burn):
		mean	sd	MC_error	val2.5pc	median	val97.5pc	start	sample
	b0	0.6845	0.1663	6.479E-4	0.3553	0.6849	1.01	10001	100000
	b1	-0.1978	0.1068	1.979E-4	-0.4107	-0.1969	0.008764	10001	100000
	b2	-0.0445	0.03244	1.347E-4	-0.1082	-0.04478	0.01946	10001	100000
	b3	0.1215	0.2338	0.001327	-0.3292	0.1185	0.588	10001	100000
	b4	-0.3682	0.2795	0.001917	-0.9122	-0.37	0.1844	10001	100000
	phi	4.204	0.5427	0.001802	3.212	4.177	5.334	10001	100000
