### ISSUE TITLE
Missing a clear guide for construct a release-like MultiBUGS package

### ISSUE THREAD

**Issue by hszest** [MultiBUGS/MultiBUGS#12]
When I was building MultiBUGS from source, I've noticed that the built package was still in separate directories, and I am not very familiar with the Black-box builder thing.

After the compilation, the 'MultiBUGS.exe' in the source directory still refuses to run on a double-click, and the MultiBUGS can run successfully using the shortcut created following the 'README.md'.

A 'Linking.odc' was located in the 'Developer' sub-directory, but it appears to me that this file is not dedicated to MultiBUGS (as 'OpenBUGS.exe' is still in the file).

I'm wondering how can I construct a release-like MultiBUGS package (just like the download on the MultiBUGS website) so I can deploy MultiBUGS on a remote server more easily?
Thx.

**Comment by hszest** [comment]
1.	Download and install: Microsoft MPI SDK & Runtime （v9.0.1）:
	https://msdn.microsoft.com/en-us/library/bb524831(v=vs.85).aspx
	
2.	Download BlackBox v1.7.1:
	http://blackboxframework.org/stable/blackbox-1.7.1.zip
	Extract files to: C:\blackbox\

3.	Download BlackBox Compiler:
	http://blackboxframework.org/makeapp/bbscript.exe
	Place this exe file in : C:\blackbox\
	
4.	Download MultiBUGS source
	https://github.com/MultiBUGS/MultiBUGS/archive/master.zip
	Extract files to : C:\MultiBUGS-master
	
5.	Make a new directory (may need admin privileges): C:\MultiBUGS\

6. 	Build MultiBUGS Modules
	C:\blackbox\bbscript.exe /USE C:\MultiBUGS-master /PAR Developer/Make.odc

7.	Link MultiBUGS Modules
	C:\blackbox\bbscript.exe /USE C:\MultiBUGS-master /PAR Developer/LinkingWindows.odc

8.	Make new directories, run:
	mkdir C:\MultiBUGS\Dynamic\Sym
	mkdir C:\MultiBUGS\Dynamic\Code

9.	Find MultiBUGS in "C:\MultiBUGS\MultiBUGS.exe"

*	The compiled file are placed at "C:\MultiBUGS\" directory

**Comment by hszest** [comment]
It turns out that the "OpenBUGS.exe" is for the MultiBUGS-flavored OpenBUGS...
Somehow the MultiBUGS-flavored OpenBUGS fixed the strange characters output problem that the original OpenBUGS has (on a Simplified Chinese ver Windows 10)

**Comment by rjbgoudie** [comment]
Thanks for pointing out this isn't clear.

If you just need a zipped binary of the development version, you can download the [latest build](
https://ci.appveyor.com/api/projects/MultiBUGS/MultiBUGS/artifacts/MultiBUGS.zip?branch=master) from Appveyor. This is created following the process you outline above.

In 53f4000cdb4aeeef46bd497c96f29ac38e200cf1 I added a link to the [README](https://github.com/MultiBUGS/MultiBUGS/blob/master/README.md) describing the process.

**Comment by rjbgoudie** [comment]
> It turns out that the "OpenBUGS.exe" is for the MultiBUGS-flavored OpenBUGS...

Yes, OpenBUGS.exe is a version of "MultiBUGS" that doesn't allow for distributed computation. It should work even if you can't install MPI, for example.

> Somehow the MultiBUGS-flavored OpenBUGS fixed the strange characters output problem that the original OpenBUGS has (on a Simplified Chinese ver Windows 10)

That's good to hear - this is probably due to upstream fixes in the BlackBox 1.7 or 1.7.1 framework.

**Comment by rjbgoudie** [comment]
d165b22af58dcced6a136a8b4c36281ff2260d38 adds to the README a description of how to create a self-contained version of MultiBUGS in a point-and-click manner.

Thanks @hszest for decoding the steps needed from `.appveyor.yml`! The method you describe is fine and correct, but `bbscript.exe` and `LinkingWindows.odc` (step 7) are only needed for automated installation and aren't needed if you are happy with point-and-click.

**Comment by hszest** [comment]
The new README file is really nice and clear for the users, thanks!
