### ISSUE TITLE
Update Microsoft MPI recommendation to v10.0 or newer (for multiple processor groups support)

### ISSUE THREAD

**Issue by ShangzhiHong** [MultiBUGS/MultiBUGS#16]
The new MS MPI v10.0 can support multiple processors now, if version <10.0, then all MultiBUGS  processes always crowd in the same processor group (i.e. all the processes run on the same physical CPU, as I tested on a two-way server)

See: https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi-release-notes

> MS-MPI v10.0 includes the following improvements and fixes. Download MS-MPI v10.0 from the Microsoft Download Center.
> **Support for utilizing multiple processor groups**

**Comment by rjbgoudie** [comment]
Yes, v10.0 looks to work fine, thanks
