### ISSUE TITLE
incomplete row of data error code

### ISSUE THREAD

**Issue by ParamjitGill** [MultiBUGS/MultiBUGS#25]
While loading a data file, I got the error message, "incomplete row of data". 
On google search, I found the following remedy
www.downloadchoice.com/common-error-messages-in-bugs-and-their
Click here to fix winbugs error incomplete row of data and related errors. ... Note: This article was updated on 2019-05-09 and previously published under ..

I don't know if the website offering the solution is legit. It asks you to download a fix. Before I do so, I want to make sure that it is.
Paramjit Gill

**Comment by rjbgoudie** [comment]
Please don't download their "solution", it sounds very dubious to me. While it is hard to say without more details, I think your data is probably mis-formatted. But hopefully you have fixed this already, given you closed the issue.

**Comment by ParamjitGill** [comment]
Thanks for the warning. I had suspected the same. The website claims that it is a Windows 10 issue.  I checked my code on an older computer (WindowsXP) and had the same warning.

I am checking my data file (267000 lines) line-by-line to figure out what is happening.
Parajit

________________________________

**Comment by rjbgoudie** [comment]
> I am checking my data file (267000 lines) line-by-line to figure out what is happening. Parajit
> […](#)

A binary search might help to isolate the problem? ie try each half the data, then half the bit that doesn't work, and so until you identify the problematic line/section
