### ISSUE TITLE
unable to link BugsWorker executable

### ISSUE THREAD

**Issue by sesillim** [MultiBUGS/MultiBUGS#35]
Hello,

I met an error message "unable to link BugsWorker executable" when click the distribute button. Could you please help me to solve this issue?

Many thanks.

Best,
Sesil

**Comment by rjbgoudie** [comment]
Hi, I imagine you long since gave up, but for future readers, I think this will have been due to permissions problem:

> Note that, within the installation directory, MultiBUGS creates a new BugsWorker.exe every time a model is run (e.g. `C:\Program Files (x86)\MultiBUGS\BugsWorker.exe`). This means you that you must have write permission for the installation directory, otherwise you will get the error “unable to link BugsWorker executable” when you try to distribute a model. Installing MultiBUGS in a different directory (e.g. `C:\Users\yourusername\MultiBUGS`) may resolve this error.
