### ISSUE TITLE
meet error when using  modelDistribute(2) 

### ISSUE THREAD

**Issue by alvincheng75** [MultiBUGS/MultiBUGS#47]
My computer's environment:
Win10 64bit with 2 core CPU and installed MS_MPI.
the whole multiBugs prog died When using modelDistribute(2) ,but can work  by modelDistribute(1).
Anyone help? Thanks a lot!

**Comment by alvincheng75** [comment]
PS:
   Task manager shows the BugsWorker.exe is working , for the CPU usage ratio is changing.

**Comment by rjbgoudie** [comment]
Hi! How did you install MultiBUGS? What version of MultiBUGS are you using?

**Comment by alvincheng75** [comment]
Now I use Windows pre-built unstable binaries, and multibugs1.0 also.
Multibugs1.0 will meet undefined real result errors while pre-built and OpenBugs won't.
Thanks.

**Comment by alvincheng75** [comment]
no install package , just unzip the downloaded pre-built version  to disk C.

**Comment by rjbgoudie** [comment]
Hi, sorry for the long delay in replying. The pre-built version is newer than 1.0, so it sounds like this problem is fixed in the pre-built version? Feel free to reopen if I have misunderstood.
