### ISSUE TITLE
Program works in OpenBUGS but not in MultiBUGS

### ISSUE THREAD

**Issue by kdd0211** [MultiBUGS/MultiBUGS#48]
I am encountering a very perplexing problem.  I am running BUGS code in OpenBUGS as well as MultiBUGS.  The reason I started using the latter is because I think my problem will likely need to be scaled up considerably but I am still in the diagnostic simulation phase.

Surprisingly, my program works in OpenBUGS but does not work in MultiBUGS.   My program right now is a simple Poisson GLM with multivariate normal priors (using a small sample size (91) and minimal MCMC iterations.  A dialogue box pops up saying Trap 066 as well as other dialogue boxes saying undefined real result.  I understand that can happen but I also can't believe that this model can't run because it actually works in OpenBUGS.  

So, what changes do I need to make to get it to run?

Below is the invocation of MultiBUGS using R.  I'm also attaching the screenshot and the BUGS code.  And to reiterate, the program works in OpenBUGS.

data<-list(n=dim(Disc)[1],m=dim(Disc)[2],x1=Lag1,y=Disc,W=W)
inits <- function(){list(alpha=0.5,beta1=0.5,mu0=0.5,tau0=1,rho=0,mu11=1,tau01=1,tau11=1)}

parameters<-c("alpha","beta1","mu0","mu11","rho","tau0")
sim1 <- bugs(data, inits, parameters, model.file="PoissonReg.txt",n.chains = 1, n.iter = 1000, n.burn=20, n.workers = 7, MultiBUGS.pgm='D:/MultiBUGS//MultiBUGS.exe',working.directory =NULL,debug=TRUE)
#sim1 <- bugs(data, inits, parameters, model.file="PoissonReg.txt",n.chains = 1, n.iter = 100, n.burn=1, working.directory = NULL,debug=TRUE)

![MultiBUGS Screen shot](https://user-images.githubusercontent.com/16838844/80430691-5b4a1680-88bd-11ea-8879-eca9604ef54a.png)
[PoissonReg.txt](https://github.com/MultiBUGS/MultiBUGS/files/4542494/PoissonReg.txt)

**Comment by rjbgoudie** [comment]
Hi, sorry for the very slow reply, and sorry you had problems. I imagine you long since gave up, so I’m closing this issue, but if not I’m happy to see if I can debug this problem.

If so, feel free to reopen this issue. It will be much easier to debug with your data `W`, `Disc` and `Lag1`. If they are are public, can you please attach to this issue; or feel free to amend/garble the data if it is not public, but please check it still runs in OpenBUGS.
