### ISSUE TITLE
Avira anti-virus incapacitates MultiBUGS 

### ISSUE THREAD

**Issue by Swronski** [MultiBUGS/MultiBUGS#52]
Avira says MultiBUGS has the pattern of HEUR/APC (cloud).  I reported it to Avira and added an exception.  Avira exceptions are here in case others have the issue: https://support.avira.com/hc/en-us/articles/360000834465-How-do-I-setup-Exceptions-for-Files-Folders-and-Processes-?utm_source=CS&utm_medium=KB

**Comment by btreut** [comment]
FYI: I had recurring false positives for BlackBox (the base executable of MultiBugs) with Avira. As far as I remember they updated their databases.

**Comment by Swronski** [comment]
Thanks.  Not sure why I got the problem but I had to attempt to install at least 8-10 times (tried reboots, different folders, etc.).  Every time I clicked on the EXE Avira jumped in and quarantined the EXE. Then I did as above.  Thanks again.

**Comment by btreut** [comment]
> why I got the problem

hmm, Avira is sometimes quite picky and BlackBox with its dynamic loader might allow for very dirty things to happen. Also MS defender once got annoyed by some version of BlackBox.

**Comment by airobot60** [comment]
> Avira says MultiBUGS has the pattern of HEUR/APC (cloud).  I reported it to Avira and added an exception.  Avira exceptions are here in case others have the issue: https://support.avira.com/hc/en-us/articles/360000834465-How-do-I-setup-Exceptions-for-Files-Folders-and-Processes-?utm_source=CS&utm_medium=KB

**Comment by rjbgoudie** [comment]
Thanks all, I’ve added a note about this to the [wiki](https://github.com/MultiBUGS/MultiBUGS/wiki). If you are able to report the false positive to Avira, please do - the more of their users that report it, the more likely they will fix their database for everyone.

**Comment by ghahnghahn** [comment]
For those who are using AVG Free, here is the way to add an exception.  I can confirm I fixed this issue with AVG on Windows 10.  Change the folder name as appropriate. https://wiki.nus.edu.sg/display/DA/Add+folder+exclusion+-+AVG+AntiVirus+Free
