### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by robbymarrotte** [MultiBUGS/MultiBUGS#63]
Hi, I don't understand the windows installation.

You wrote:

<4. Make a new shortcut to the BlackBox.exe file in the newly-installed BlackBox directory (right-click on BlackBox.exe, choose "Create shortcut"). Then, right click the newly-created shortcut, choose "Properties", and choose the "Shortcut" tab. Then add the following text to the Target box, with the paths C:\Program Files (x86)\BlackBox Component Builder 1.7\BlackBox.exe (path to BlackBox.exe) and C:\MultiBUGS-master (path to the MultiBUGS directory) changed to match wherever you installed BlackBox and MultiBUGS:>

And then you give some code that we run in something? CMD I assume? Or do we even run this code?
mpiexec -n 1 "C:\Program Files (x86)\BlackBox Component Builder 1.7\BlackBox.exe" /USE "C:\MultiBUGS-master"

I don't understand the steps too well either. You cannot add two paths to the Target box. So I cannot add:
"C:\Program Files (x86)\BlackBox Component Builder 1.7\BlackBox.exe" and "C:\MultiBUGS-master" together in the target box. Do you mean, put the first path in the target path and put the second in Start in? I tried this and it also doesn't seem to work.

Thanks

Robby

**Comment by rjbgoudie** [comment]
Hi,

As far as I know, it is not correct that “You cannot add two paths to the Target box”. You should able to include the full line of code in the `Target` box:

```
mpiexec -n 1 "C:\Program Files (x86)\BlackBox Component Builder 1.7\BlackBox.exe" /USE "C:\MultiBUGS-master”
```

However, note this is only needed if you want to compile the code from source — if you use the released version on https://www.multibugs.org/download then none of this is needed.

**Comment by robbymarrotte** [comment]
Hi,
I added this code in the path and the shortcut doesn't actually open blackbox anymore.
I'll try the compiled version.
Thanks

**Comment by robbymarrotte** [comment]
In addition the download for multibug 2.0 potentially has a virus.

**Comment by rjbgoudie** [comment]
> In addition the download for multibug 2.0 potentially has a virus.

Yes, unfortunately some virus software misclassify the underlying "BlackBox" software framework used by BUGS as a virus. We have been contacting anti-virus companies to try to fix the false-positive detection of MultiBUGS - several have now corrected their definition files, but unfortunately this is no guarantee the problem will not arise again in the future. Which virus software are you using?

**Comment by rjbgoudie** [comment]
> Hi,
> I added this code in the path and the shortcut doesn't actually open blackbox anymore.

I suspect you need to make sure paths within that line are changed to match to wherever you installed BlackBox and MultiBUGS on your computer

> I'll try the compiled version.
> Thanks

**Comment by robbymarrotte** [comment]
Unfortunately its windows security and I cannot bypass it because this is a company computer.

**Comment by rjbgoudie** [comment]
> Unfortunately its windows security and I cannot bypass it because this is a company computer.

Do you mean Microsoft Defender?

**Comment by robbymarrotte** [comment]
Well it says windows security for me, but I guess its likely windows defender.

**Comment by rjbgoudie** [comment]
> Well it says windows security for me, but I guess its likely windows defender.

Can I ask which version of Windows you are using, so I can report this false-positive to Microsoft accurately? Many thanks

**Comment by robbymarrotte** [comment]
Windows 10 pro

**Comment by rjbgoudie** [comment]
Thanks, have reported this to Microsoft. Hopefully they will fix the false positive detection.

**Comment by rjbgoudie** [comment]
Looks like Microsoft Defender no longer falsely identifies MultiBUGS as a virus: https://www.virustotal.com/gui/file/7821aa1481157adb0889d6c1d5160cd2682dadd010316dec6f7d9e24903bd554/detection

**Comment by robbymarrotte** [comment]
Awesome thanks!

**Comment by robbymarrotte** [comment]
> Looks like Microsoft Defender no longer falsely identifies MultiBUGS as a virus: https://www.virustotal.com/gui/file/7821aa1481157adb0889d6c1d5160cd2682dadd010316dec6f7d9e24903bd554/detection

I just tried downloading it again and chrome blocked it...

**Comment by iadenisov** [comment]
To sign application with digital certificate can help. 
I had some experience with Thawte Code Signing Certificate.
I put the instructions here:
https://translate.google.ru/translate?hl=&sl=ru&tl=en&u=https%3A%2F%2Fmolpit.org%2Fblog%2FDIA00159
